### PR TITLE
Update processors, Scala, sbt, libraries, etc. and get most tests running

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
There are about three tests to go.

**Comment by kwalcock** [comment]
The tests are all passing now, sometimes because they have been disabled.  Another pass should be made eventually to take care of failingTests.

**Comment by kwalcock** [comment]
This time it didn't run out of memory, but "Step is killed (canceled)" after what looks like an hour.  Perhaps there is a time limit.  I don't think it took that long on my computer, but that might have more processors than what is being used now.  The program can be sped up substantially, but it would be nice to do that at our leisure with testing active in the meantime.  I'll check for relevant settings.

**Comment by adarshp** [comment]
@kwalcock  - We can increase the time limit. Waiting on @vincentraymond-ua to make me an admin on the Drone instance so I can do that.

**Comment by adarshp** [comment]
@kwalcock - I've increased the timeout to 4 hours and restarted the build. I'll also look into whether there is a limit on the number of processors that can be used.

**Comment by adarshp** [comment]
I'm seeing the error I had seen previously:

```
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
173s
13	[error] http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar: wrong checksum: /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar (expected SHA-1 d3cfa151e5debeb4bcaec5648588d299f36dc8bb in /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/.model-streamed-trigram-ser_2.12-1.0.0.jar__sha1, got 56c6fe7b2f75fd24925c72ef34e441c342b014ba)
173s
14	[error] 
173s
15	[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
173s
16	[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
173s
17	[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
173s
18	[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
173s
19	[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
173s
20	[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
173s
21	[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
173s
22	[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
173s
23	[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
173s
24	[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
173s
25	[error] 	at java.lang.Thread.run(Thread.java:750)
173s
26	[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$WrongChecksum: wrong checksum: /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar (expected SHA-1 d3cfa151e5debeb4bcaec5648588d299f36dc8bb in /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/.model-streamed-trigram-ser_2.12-1.0.0.jar__sha1, got 56c6fe7b2f75fd24925c72ef34e441c342b014ba)
173s
27	[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$validateChecksum$4(FileCache.scala:142)
173s
28	[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
173s
29	[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
173s
30	[error] 	at scala.util.Success.map(Try.scala:213)
173s
31	[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
173s
32	[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
173s
33	[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
173s
34	[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
173s
35	[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
173s
36	[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
173s
37	[error] 	at java.lang.Thread.run(Thread.java:750)
173s
38	[error] (grounding / update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
173s
39	[error] http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar: wrong checksum: /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/model-streamed-trigram-ser_2.12-1.0.0.jar (expected SHA-1 d3cfa151e5debeb4bcaec5648588d299f36dc8bb in /root/.cache/coursier/v1/http/artifactory.cs.arizona.edu%3A8081/artifactory/sbt-release/org/clulab/model-streamed-trigram-ser_2.12/1.0.0/.model-streamed-trigram-ser_2.12-1.0.0.jar__sha1, got 56c6fe7b2f75fd24925c72ef34e441c342b014ba)
173s
40	[error] Total time: 151 s (02:31), completed Nov 7, 2022 4:50:02 PM
173s
41	[0J	174s
```

**Comment by kwalcock** [comment]
It's having problems downloading that 2gb file.  I wonder whether something might be cutting off the download.  It attempted three times and still finished in 2.5 minutes, so it doesn't seem like it would have fetched the entire file.  It worked twice for me last night.  I'll try locally and see if anything looks suspicious.  In some cases people have had firewall problems trying to get at port 8081.  Could something like that be happening?

**Comment by kwalcock** [comment]
The download is working OK for me with both a check using wget and a new download with coursier.  The hash codes checked out OK.  I'm going to just try again.

**Review by enoriega — APPROVED** [review]
@kwalcock Thanks for doing this massive amount of work. It looks good to me.

**Comment by enoriega** [comment]
@kwalcock Are the CI issues still in the process of being fixed? If they're done, I will proceed to merge

**Comment by enoriega** [comment]
@kwalcock @adarshp I am seeing an error in Drone that doesn't match the errors I get when I clone `kwalcock/automates_porting` and run the `sbt webapp/test` manually.

On Drone, there is a conflict between library versions, locally, it seems the following files are not in the version:

- `./src/main/resources/frequentWords.tsv`
- `/automates/automates/text_reading/src/main/resources/vectors.txt`

The latter file is a w2v model has to be added manually. This is inherited from automates' grounding and I suggest we get rid of it, along with the test suite it uses it, as we already have an embedding model added as a maven dependency.

**Comment by kwalcock** [comment]
As far as I know, frequentWords.tsv is at github in the branch.  vectors.txt has been replaced by glove in a resource that is downloaded as per instructions in build.sbt.

**Comment by enoriega** [comment]
@kwalcock I am digging around and it looks like we will require to rework most of the test scripts. It is not that the tests are broken by the changes, but that they have always been broken.

The majority of the test scripts are inherited from automates, so we will have to go and check them to see which will be updated and which can be deleted.

To avoid making the scope of this PR even larger, can we mark them as "ignored" to clear CI, and merge the changes? Then we can start a new branch where we work through the test suites.

**Comment by kwalcock** [comment]
It looks like my increment of the sbt version backfired and created some dependency problems, which I'll fix.  Sorry.

**Comment by kwalcock** [comment]
FWIW the test suite runs on my computer in 4.5 minutes.  The loading of multiple vector files is inefficient and will soon change, but it shouldn't be taking an hour.  I did just see an error with 8gb so am increasing to 10.

**Comment by kwalcock** [comment]
Maybe that will work for now.  As the tests and code change we'll at least notice when we break things.

**Comment by adarshp** [comment]
@kwalcock @enoriega  - the tests seem to be passing now (they run in 12 minutes!) so I will go ahead and merge this PR.

**Comment by enoriega** [comment]
Thanks @adarshp and @kwalcock

**Pull request merged**
