### PR TITLE
Milestone 6 PR

### PR DESCRIPTION
**Pull request by titomeister**
This branch adds changes and fixes for the Milestone 6 release.
For details on the changes and fixes see the Milestone 6 report.

### CODE REVIEW

**Comment by adarshp** [comment]
@titomeister  - should the skema/gromet/primitive_map.py file be in the PR? I thought we were going with a YAML file instead (https://github.com/ml4ai/skema/pull/119)

**Comment by vincentraymond-ua** [comment]
@adarshp - I believe that Tito is still using a Python based version of the primitive map for Gromet generation.

**Comment by adarshp** [comment]
@vincentraymond-ua  - got it, thanks for clarifying!

**Review by vincentraymond-ua — APPROVED** [review]
@titomeister - Looks good! With the change to small change to bucky_v2 (adding `nonvaccs = 1.0`) I've confirmed that all models are going through to Gromet again. 

I also noticed some old print statements we were using for debugging and have gone ahead and removed those.

**Pull request merged**
