### PR TITLE
[CI] Use fork with fix to jlumbroso/free-disk-space/issues/9

### PR DESCRIPTION
**Pull request by myedibleenso**
## Summary of changes
Resolves a CI issue related to an action that removes unused packages to create additional space on the runner for docker builds

### CODE REVIEW

**Comment by myedibleenso** [comment]
FYI @enoriega @kwalcock

**Review by enoriega — APPROVED** [review]
LGTM

**Comment by kwalcock** [comment]
Thanks for tracking that down.  Does there need to be an update after the PR is merged into the official version?

**Comment by myedibleenso** [comment]
@kwalcock , we might want to update it then.  Alternatively, we might just want to fork it (perhaps to `lumai`?) and use that version.  It shouldn't need to change very much and hopefully we can phase it out completely after reducing the image size for TR.

**Pull request merged**
