### PR TITLE
Build and publish project docker images to lumai dockerhub namespace

### LINKED ISSUE #221: [docker] publish skema images to `lumai` namespace on dockerhub
For easy and consistent reference, we've elected to publish skema Docker images to the `lumai` namespace on Dockerhub.  To start, the following images will be published:

- `lumai/askem-skema-py`
- `lumai/askem-skema-rs`
- `lumai/askem-skema-text-reading`
- `lumai/askem-skema-img2mml`

Initially, these images will be published only for the linux/amd64 platform.

```[tasklist]
### Tasks
- [ ] GitHub Action for building and publishing project Docker images to Dockerhub
- [ ] Provision project repos on Dockerhub and create a `lumaiaskem` user for CI
```

### PR DESCRIPTION
**Pull request by myedibleenso**
This GitHub Action is intended to build the following images whenever a PR is opened:

- `lumai/askem-skema-py` (contains program analysis, moviz, etc. components)
- `lumai/askem-skema-rs`
- `lumai/askem-skema-text-reading`
- `lumai/askem-skema-img2mml`

Any push (including a merged PR) to `main` will publish those four images to public repos on Dockerhub.  Each image will be tagged with a) `latest` and b) its short Git commit hash.

Resolves #221

### CODE REVIEW

**Comment by myedibleenso** [comment]
It might be worth considering how best to speed up these builds (I suspect GitHub Action's cache won't help much, as we'll quickly blow through our allowance).  Currently, the `-rs` (6m+) and `-text-reading` (10m+) images are the most time consuming steps of this workflow.  For the text reading image, one solution could be to create a `skema-base-images` repo where we publish a `lumai/askem-skema-text-reading-base` containing https://github.com/ml4ai/skema/blob/1d6e4bf814fa755ff00a5a32f692e3b7a291dd86/skema/text_reading/text_reading/Dockerfile#L1-L51 which is unlikely to change frequently.

We would then alter https://github.com/ml4ai/skema/blob/1d6e4bf814fa755ff00a5a32f692e3b7a291dd86/skema/text_reading/text_reading/Dockerfile#L1 to reference that base image.

**Comment by myedibleenso** [comment]
FYI @myedibleenso @cl4yton @enoriega @jastier

**Comment by adarshp** [comment]
@myedibleenso - Slow Docker builds are a known issue with Rust. I've looked into ways to speed it up, but haven't tried any methods yet. This one seemed promising: https://www.lpalmieri.com/posts/fast-rust-docker-builds/ but I don't know when I will be able to get around to it.

**Comment by myedibleenso** [comment]
@adarshp , thanks for sharing.  I can open a low priority issue to track this along with another centered on optimizing the build for the text reading image.  We should probably tackle them in descending order of build time.

**Pull request merged**
