### PR TITLE
Drone.io CI support

### PR DESCRIPTION
**Pull request by vincentraymond-ua**
Adds `.drone.yml` file to the root of the repository for Drone.io continuous integration support

### CODE REVIEW

**Review by adarshp — APPROVED** [review]

**Comment by kwalcock** [comment]
Yes, I can.  They can probably be run directly on github and I notice there is already a .github/workflows/ directory.  It would be good to get the tests passing locally first.  Right now I am waiting on #16 to get sorted out.

**Comment by adarshp** [comment]
@kwalcock  - I was planning on phasing out Github Actions (configured using the YAML files in `.github/workflows` in favor of using the `.drone.yml` config file to run our CI on local servers (we can have some more control over the runners, allocate additional resources if necessary, and potentially reduce wait time).

**Comment by adarshp** [comment]
@kwalcock  - re: local testing and waiting for #16 to get sorted out - makes sense. Let's wait on that.

**Comment by kwalcock** [comment]
OK.  I don't know about drone yet.  The clulab is testing a couple of projects locally with jenkins, but the other is probably not too difficult and I'll start looking into it.

**Pull request merged**
