### PR TITLE
[TextReading] Added the TR evaluation endpoint

### PR DESCRIPTION
**Pull request by enoriega**

### CODE REVIEW

**Comment by enoriega** [comment]
Closes #515

**Comment by enoriega** [comment]
Closes #515

**Comment by myedibleenso** [comment]
Wish you'd waited to merge this...

**Comment by enoriega** [comment]
Oh no. I swear the tests had already passed when I did it ...

**Comment by myedibleenso** [comment]
It's fine.  It's just that this one had conflicts with other PRs that had been opened earlier and already approved.

**Pull request merged**
