### PR TITLE
Memory map local word embeddings

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
This is configured to work for the MiraEmbeddingsGrounder.  The goal is to use it in other places as well, but this is a good point to check in.

**Comment by kwalcock** [comment]
I'm still going to add a finalizer to this.

**Comment by kwalcock** [comment]
@myedibleenso, you may be interested.

**Comment by kwalcock** [comment]
After reading https://mapdb.org/blog/mmap_files_alloc_and_jvm_crash/, I decided that the finalizer should be skipped.  It says

> There is no official way to close memory mapped buffer. JVM releases file handles only after ByteBuffer gets garbage collected. If GC is not invoked for some time (large free heap), you will run out of file handles.

If my finalizer is being called, then most likely the buffers are about to be closed anyway and the connections are soon to follow.  My mucking around in it will only complicated the situation.  We expect only a handful of memory mapped files anyway.

**Review by enoriega — APPROVED** [review]
Really nice job! @kwalcock

**Pull request merged**
