### PR TITLE
[Text Reading] Removed the legacy Dockerfile

### PR DESCRIPTION
**Pull request by enoriega**
## Context

We have two dockerfile definitions for the text reading system. One of them is abandoned and was superseded by the `webapp` image defined in `docker.sbt`. 

This PR deletes the unused dockerfile to make things simpler in the future

### CODE REVIEW

**Comment by myedibleenso** [comment]
@enoriega , #451 introduces conflicting changes to CI.  I think we should review and merge that one first.  To avoid conflicts, can you update your PR to stick with the version of `.github/workflows/docker.yml` currently on `main`?

**Comment by enoriega** [comment]
@myedibleenso Yes. It is back in sync with `main`

**Comment by enoriega** [comment]
@myedibleenso this should be good to merge now.

**Comment by kwalcock** [comment]
Thanks!  I appreciate the TLC it's getting.

**Review by myedibleenso — APPROVED** [review]

**Pull request merged**
