### PR TITLE
MATLAB to GroMEt testing

### PR DESCRIPTION
**Pull request by jastier**
## MATLAB to GroMEt testing
This PR adds GroMEt translation to all pytest cases in the Tree-Sitter MATLAB translator.  This was done as part of the fix for a bug that was happening when generating Model Coverage Reports.  The CAST to GroMEt converter was reporting correctly that the "list" type is not supported, switching to the corresponding enumeration fixed that issue.  

## Relavant Features:
- Each pytest case now includes GroMEt translation.
- Got rid of some outdated static method typing calls.
- `LiteralValue `data types are now CAST enumerations instead of hard-coded strings.
- Removed the handler for `Range `Tree-sitter syntax nodes, these nodes are managed by iterator routines
- Turned off the pytest series related to loops temporarily

Related to issue #725 
Partially resolves issue #764

### CODE REVIEW

**Comment by titomeister** [comment]
@jastier I think Gus wants us to mark issue resolution using
"Resolves ###"

Can you add that to your PR Description? I see you have the issues mentioned, but I think you just need the right formatting.
Resolves #725 
Resolves #764

**Comment by jastier** [comment]
Main description edited to include related and partially resolved issues.

**Review by titomeister — APPROVED** [review]
Looks good. Thank you Joseph!

**Comment by myedibleenso** [comment]
@titomeister , can you please try resolving these conflicts so that we can merge this PR?

**Comment by myedibleenso** [comment]
@titomeister , it looks like the tests are now failing.  These were working as of [9933c53](https://github.com/ml4ai/skema/pull/765/commits/9933c532af0e88cf442b6fa13727c170b3a9b2c2).  Can you please take another look?

**Comment by titomeister** [comment]
@myedibleenso I'm looking. For some reason a bunch of places just have outdated pieces of code. I've tried merging what's in main but it doesn't seem to fix it. Trying to fix manually now.

**Pull request merged**
