### PR TITLE
Relaxing requirement for a single top-level mrow element

### PR DESCRIPTION
**Pull request by adarshp**
This PR:
- relaxes the requirement for a `math` element to have a single top-level `mrow` in order to produce Petri nets/Regnets.
- Updates the MML parser to handle leading/trailing whitespace within element contents.
- Adds a test case for the mml2amr pipeline corresponding to Lotka-Volterra equations.

### CODE REVIEW

**Review by myedibleenso — CHANGES_REQUESTED** [review]
Thanks, @adarshp !  

Would it be possible to add a parsability test using the pMML provided in https://github.com/ml4ai/skema/issues/289#issue-1781305406 ?

**Comment by adarshp** [comment]
@myedibleenso  - The pMML in https://github.com/ml4ai/skema/issues/289#issue-1781305406 is decidedly less than ideal, and does not render to anything resembling the original Lotka-Volterra equations. You can test it here: https://codepen.io/bqlou/pen/yOgbmb. Hopefully this will be fixed by the new model being trained by @ualiangzhang .

I've updated the parser to handle leading/trailing whitespace for element contents, and added a [test](https://github.com/ml4ai/skema/blob/0f81077ee6bf2b52c9bf27b01129e8895f4b2b8b/skema/skema-rs/mathml/src/acset.rs#L548-L567) with [manually written pMML](https://github.com/ml4ai/skema/blob/adarshp/top-level-mrow-req-relaxation/skema/skema-rs/mathml/tests/mml2amr_input_1.json) that does match the Lotka-Volterra equations.

**Review by myedibleenso — APPROVED** [review]
Thanks, @adarshp .

**Comment by myedibleenso** [comment]
>The pMML in https://github.com/ml4ai/skema/issues/289#issue-1781305406 is decidedly less than ideal, and does not render to anything resembling the original Lotka-Volterra equations. You can test it here: https://codepen.io/bqlou/pen/yOgbmb. Hopefully this will be fixed by the new model being trained by @ualiangzhang .

FYI @cl4yton

**Comment by myedibleenso** [comment]
@ualiangzhang , as you all train new models, I suggest evaluating them against the following files (among other things of course):

- [lotka-volterra-eq-1.png](https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/c2404523e7bb0a0af7f773ac95881bb8f1700da7/equations-rest/data/images/lotka-volterra-eq-1.png)
- [lotka-volterra-eq-2.png](https://github.com/ml4ai/ASKEM-TA1-DockerVM/blob/c2404523e7bb0a0af7f773ac95881bb8f1700da7/equations-rest/data/images/lotka-volterra-eq-2.png)

**Comment by ualiangzhang** [comment]
@myedibleenso @adarshp I am currently working on deploying the updated model and will proceed with testing the equation images as you suggested. Hopefully, we will have a more reliable and robust img2mml service before the hackathon. Thanks!

**Pull request merged**
