### PR TITLE
Changed the default address for the inner MIT service

### PR DESCRIPTION
**Pull request by enoriega**

### CODE REVIEW

**Comment by enoriega** [comment]
@myedibleenso just wanted to verify that the endpoint is using `http` not `https`

**Comment by myedibleenso** [comment]
Maybe you want to deploy that other TR service on UA infra as well?

**Review by myedibleenso — CHANGES_REQUESTED** [review]
As I understand it, I believe the plan is now to update the ENV defaults to use addresses for the TR services deployed on UA infrastructure.

**Comment by enoriega** [comment]
@myedibleenso Yes. We actually end up using MIT's deployment as default value. Thanks!

**Pull request merged**
