### PR TITLE
Include working MathJax server in docker image

### LINKED ISSUE #256: [docker] add MathJax server dependencies for img2mml
`img2mml` relies on calls to a MathJax server, but these dependencies (Node JS + JS libraries) are not included in our docker image nor our dev environment setup instructions.

### LINKED ISSUE #257: [img2mml] MathJax server `/tex2mml` fails to process requests
`/tex2mml` should accept JSON POSTed of the form `{"tex_src": "E = mc^{2}"}`, but fails to parse such JSON.

### PR DESCRIPTION
**Pull request by myedibleenso**
## Summary of changes
- Include MathJax server deps (Node and JS libs) in docker image ( Resolves #256 )
- Corrected bug in parsing JSON data in `tex2mml` endpoint ( Resolves #257 )
- Update `docker-compose.img2mml.yml` to include networked MathJax and unified REST API for latex2mml + img2mml services
- Update development environment setup instructions
- mml response is now xml (avoids funky escapes previously encountered)

### CODE REVIEW

**Comment by myedibleenso** [comment]
@jastier  and/or @ualiangzhang , can one of you please review this PR?

**Comment by ualiangzhang** [comment]
Hi @myedibleenso,

Regarding line 48 of /skema/skema/img2mml/api.py, the correction should be made as follows: webservice = protocol + host + ':' + str(port) since the port value is an integer.

As for the img2mml service, it appears to be functioning well. However, the latex2mml service was displaying irrelevant quotation marks. For instance, in the test case of E = mc^{c}, the returned MathML output would include unnecessary quotation marks as shown below:

`<math xmlns=\"http://www.w3.org/1998/Math/MathML\" display=\"block\" alttext=\"&quot;E = mc^{c}&quot;\"> <mo>&quot;</mo> <mi>E</mi> <mo>=</mo> <mi>m</mi> <msup> <mi>c</mi> <mrow class=\"MJX-TeXAtom-ORD\"> <mi>c</mi> </mrow> </msup> <mo>&quot;</mo></math>`

However, after reverting back to the original mathjax_server.js and latex2mml.py files in the main branch, this issue no longer persists. Of course, we need to fix line 47 of /skema/skema/img2mml/api.py as webservice = protocol + host + ':' + str(port) first.


If you have any further questions or concerns, please feel free to let me know. Thanks!

**Comment by myedibleenso** [comment]
Thanks, @ualiangzhang ! 

I think I didn't run into the type error, because I was always setting the port in my tests using the env variable and all env variables are strings.  I've made the change you suggested.  I should've tested the default. 

Your comment about the quotes made me take a closer look at the response types.  I think I've managed to simplify things by setting the content type of the response as XML (see the unified REST API in `eq2mml.py`):

image


You should be able to reproduce this by running `docker-compose -f docker-compose.img2mml.yml up --build`.

**Comment by ualiangzhang** [comment]
Hi @myedibleenso. Thank you for your response! I checked the updated eq2mml.py. latex2mml is doing well now. But, when testing /image/mml, I got this error after uploading an equation image: 
```
Please correct the following validation errors and try again.
Value must be a string
```
Could you please take a look? Thanks!

**Comment by myedibleenso** [comment]
Thanks , @ualiangzhang , for your help debugging.  I believe the issue you mentioned has been taken care of.

**Comment by ualiangzhang** [comment]
Thank you, @myedibleenso! I'm always glad to be of assistance. :)

**Pull request merged**
