### PR TITLE
[CODE2FN] Preprocessor for Fortran->CAST pipeline

### LINKED ISSUE #156: [Fortran] Create primitive set
Currently, we are not handling language features such as `PRINT` for Fortran.  To cover these language features comprehensively, we need a primitive set (following our approach elsewhere).

Note that this issue ties to Milestone 9.

### LINKED ISSUE #185: [fortran] Adding front-end support for handling Fortran compiler directives
The following Fortran compiler directives are not yet supported:
- `#if`,`#ifdef`,`#elif`,`#else`

- [ ] Write script to identify and translate instances of header (or other file) inclusion that assumes system-context locations
  - [x] translate to be *local* references to included files
  - [ ] collect all local file references and provide as summary output for user to manually collect the needed libraries
  - [ ] Develop convention for how included files will be locally managed/stored
- [x] Add support for using gcc/gfortran pre-compiler to handle all pre-compiler directives
- [x] Develop convention for managing generated post-pre-compiler processing
  - [x] option to generate intermediate products (e.g., pre-processing script that handles line continuations and system-includes); in separate directory for each file; for multi-file system, mirror source directory tree structure; can specify root of generate intermediate products

### LINKED ISSUE #194: [fortran] Create pre-preprocessor script to identify unsupported idioms
Create script to be run along with pre-pre-processing that identifies and bookkeeps instances of Fortran patterns that we do not yet handle; only consider the source code / ignore comments. This could help drive unit test dev.

Bookkeeping:
- record the type (tree-sitter vs. idiom)
- idiom name (e.g., coarray), 
- instance file/line number

Two types of patterns:
- due to lack of tree-sitter Fortran parser support
- consider also adding idioms we don't yet support, but if they're hard to specify by simple regex, then don't bother.

### PR DESCRIPTION
**Pull request by vincentraymond-ua**
Creates script for preprocessing Fortran source code to convert it to a form that can be parsed correctly by tree-sitter. The preprocessor handles the following: 
1. Checking for missing files
2. Running GCC to automatically handle preprocessor directives 
3. Checking for unsupported idioms
4. Fixing some unsupported idioms (system level includes, continuation lines) 

Adds idioms_regex.txt, a list of regex matching idioms not supported by tree-sitter:. Current support for matching:
- '|' Continuation Lines
- Coarrays
- System level include directives (#include <...>)

Adds fortran_builtins.yaml, a Fortran equivalent of python_builtins.yaml

Resolves #156 
Resolves #194 
Resolves #185

### CODE REVIEW

**Review by myedibleenso — CHANGES_REQUESTED** [review]
Thanks, @vincentraymond-ua .  I'd like to see some minimal documentation demonstrating the intended usage referencing a set of files in a top-level `examples` directory.

For now, please add this documentation as a page in the project wiki.  Later we may migrate that to a page on the project website.

Also, we need to think about how this should be tested in the future.  One option might be to use something like [`pytest-executables`](https://pytest-executable.readthedocs.io/en/stable/how-to-use.html#run-the-exe-and-do-default-regression-checks) to detect regressions.  

Can you please open a separate issue for testing this preprocessor?

**Comment by vincentraymond-ua** [comment]
@myedibleenso - Will do!

**Comment by vincentraymond-ua** [comment]
@myedibleenso - When you refer to the project wiki, are you referring to the [automates ](https://github.com/ml4ai/automates/wiki)wiki or the [skema_lum ](https://github.com/lum-ai/skema-lum/wiki)wiki? I've also gone ahead and added the requested documentation as a README file in the preprocessor directory.

**Review by myedibleenso — APPROVED** [review]
LGTM.  Thanks for adding [that documentation](https://github.com/ml4ai/skema/wiki/Using-the-tree-sitter-preprocessor), @vincentraymond-ua !

**Review by titomeister — APPROVED** [review]
Looks good to me!

**Pull request merged**
