### PR TITLE
Additional parsers can be handled

### PR DESCRIPTION
**Pull request by deepsana**
## Summary of Changes
Parser can parse:
- Down Arrow e.g. I^{↓} 
- Msubsup Integral e.g. \int_{x_1}^{x_2}  
- Laplacian: e.g. \nabla^2
- Closed surface integral:  \oiint_S
- Second order partial differential equation 

### Related issues

Resolves ???

### CODE REVIEW

**Comment by myedibleenso** [comment]
@vincentraymond-ua @Free-Quarks , we need to get the Rust image fix merged, as new PRs will start to run into this.

**Comment by vincentraymond-ua** [comment]
@Free-Quarks This looks like a different dependency issue than the one that was merged in this PR https://github.com/ml4ai/skema/pull/786. I'm not `ahash` in any of the cargo.toml files, so I'm not sure where its being pulled in from.

**Comment by myedibleenso** [comment]
Ah, my mistake.  I'd missed #786 .

**Comment by Free-Quarks** [comment]
I'll look into it and push a fix to this branch. I don't think it should be anything major

**Review by Free-Quarks — APPROVED** [review]
LGTM!

**Pull request merged**
