### PR TITLE
Addresses Built-in Map Generation

### PR DESCRIPTION
**Pull request by titomeister**
This PR addresses an issue with how the Python built-in map is created.

Before, the built-in map stored in `skema/program_analysis/PyAST2CAST/python_builtins.yaml` couldn't be loaded on the fly. This was due to an incorrect way of trying to load the yaml file.
This has been fixed now, and the yaml file can be loaded appropriately using the "__file__" global variable.

In addition, a simple test case was created to test the functionality.

### CODE REVIEW

**Comment by myedibleenso** [comment]
@titomeister , can you please merge `main` into this branch?  I think that may take care of the CI issue.

**Comment by adarshp** [comment]
@titomeister  - I suggest making `filename` fully uppercase (to denote that it's a global variable) and having a more descriptive name (e.g. `BUILTINS_FILENAME`)

**Comment by titomeister** [comment]
> @titomeister - I suggest making `filename` fully uppercase (to denote that it's a global variable) and having a more descriptive name (e.g. `BUILTINS_FILENAME`)

I've gone ahead and done that. Thank you for the suggestion @adarshp !!

**Review by vincentraymond-ua — APPROVED** [review]
@titomeister - Looks good after the updates and should be good to go!

**Pull request merged**
