### PR TITLE
Jastier/refactor_CAST2FN

### PR DESCRIPTION
**Pull request by jastier**
Refactored CAST2FN into CAST/Fortran

Please test this code to be sure no linkages have broken.

### CODE REVIEW

**Comment by myedibleenso** [comment]
Thanks, @jastier !  Curious what others think: my preference would be to lower case the directories corresponding to frontends (`Fortran` -> `fortran`); maybe even CAST (`CAST` -> `cast`).  @vincentraymond-ua @titomeister @cl4yton ?

**Comment by jastier** [comment]
Sure @myedibleenso , these would not be hard changes to make.   We would end up with something like this:

```
CAST
├── fortran
├── gcc
├── matlab
└── python_ast
```
or perhaps
```
cast
├── fortran
├── gcc
├── matlab
└── python_ast
```

 @vincentraymond-ua @titomeister @cl4yton 
Thoughts?

**Comment by vincentraymond-ua** [comment]
@jastier - It looks like you've moved CAST2FN to the fortran directory instead of TS2CAST. CAST2FN is the CAST->Gromet pipeline.

**Comment by cl4yton** [comment]
Re. naming: Good point, @myedibleenso 
I support moving to lower-case. However, let's keep references to CAST and FN (for Function Network) capitalized, so as to distinguish from "cast" (as in, conversion) and "function", respectively.

@vincentraymond-ua and @titomeister, what do you two think of this?

**Comment by vincentraymond-ua** [comment]
@cl4yton - I also support keeping references to CAST and FN capitalized.

**Comment by jastier** [comment]
@vincentraymond-ua 

Good catch.

Closing out this PR, will re-submit with the correct directory moved.

**Pull request closed without merging**
