### PR TITLE
Moviz dev

### PR DESCRIPTION
**Pull request by isha-talegaonkar**
Code for visualization of expressions, while loops, functions, conditions

### CODE REVIEW

**Review by cl4yton — CHANGES_REQUESTED** [review]
Hi @isha-talegaonkar ! Thank you for starting this PR. I do ask that you make the following changes:
(1) It looks like somehow the PR includes files from the automates repo (including files that I don't think are related to your moviz work). I think the PR should only include changes to the moviz content in the skema repo. Do you know how the automates files are being included, and can they be removed from the PR?
(2) Please avoid including files that are automatically generated. For example, you are including a number of .png images under moviz/static/ . These can lead to bloat in the repository.

Let me know if you have any follow-on questions or want to discuss by zoom.
(cc @adarshp @kisaacs )

**Comment by isha-talegaonkar** [comment]
Hi @cl4yton, 

Thank you for the suggestions. 
I have made all the changes requested.

**Review by adarshp — CHANGES_REQUESTED** [review]
@isha-talegaonkar - still a few things to be removed.

- Do you need the `scripts` directory? If not, could you remove it?
- Could you please remove the `venv` directory as well? We don't want to check in virtual environments into git...

**Comment by isha-talegaonkar** [comment]
@adarshp Made the changes requested.

**Review by adarshp — APPROVED** [review]

**Pull request merged**
