### PR TITLE
[rust] fix lint warnings

### PR DESCRIPTION
**Pull request by myedibleenso**
## Summary of Changes

 Automatically fixes for lint warnings reported by `rustc`:

```bash
cargo fix --all-targets
```
### Related issues

N/A

### CODE REVIEW

**Comment by Free-Quarks** [comment]
This reminds me I've been meaning to add this command to my VSCode on save commands.

**Comment by ualiangzhang** [comment]
@deepsana Can you take a look at these changes on Parser-related parts? Thanks!

**Comment by ualiangzhang** [comment]
@myedibleenso The changes in `expression.rs` are doing okay. I gave this PR approval. But if @Free-Quarks or @deepsana wants to change anything, please send requests. Thanks!

**Review by ualiangzhang — APPROVED** [review]

**Comment by myedibleenso** [comment]
@Free-Quarks @ualiangzhang , I think I will just close this at this point.

**Pull request closed without merging**
