### PR TITLE
[execution_engine] Initial testing support for execution engine and Memgraph instance for CI

### LINKED ISSUE #543: [execution_engine] Initial testing framework for execution engine
There are a few steps we need to take before we are able to add CI unit tests for the execution engine:

1. Run Memgraph instance for CI, see: [https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#running-jobs-in-containers](https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#running-jobs-in-containers)
2. Support going directly from source -> execution output
3. Adds tests to test initial values and history of parameters during execution.

### PR DESCRIPTION
**Pull request by vincentraymond-ua**
## Initial testing framework for execution engine
Creates initial tests for execution engine. Before testing could be supported the following framework needed to be added:

1. Adding a Memgraph instance to Github workflow (see below)
2. Adding step for source->Gromet ingestion
3. Adding step for Gromet->Memgraph ingestion

### Additional Updates
- Replaces `--filename` command line option with `--source_path`
- Adds additional query `reset_state` to reset Memgraph state
- Adds support for List and None primitive types
- Fixes bug when node._id == 0

## Memgraph instance for CI
There is now a Memgraph instance available when running unit tests in Github Workflows. The Memgraph instance can be accessed through `localhost:7687`

### Writing unit tests that access Memgraph 
Pytest unit tests requiring a Memgraph database should be marked with the ci_only marker.
``` Python
@pytest.mark.ci_only
def test_memgraph:
    assert True
```

If running Pytest locally without a Memgrpah instance running, you can then ignore these tests using:
``` Bash
pytest -m "not ci_only"
```
Resolves #543

### CODE REVIEW

**Review by myedibleenso — APPROVED** [review]
LGTM.  Thank you, @vincentraymond-ua !

**Review by myedibleenso — CHANGES_REQUESTED** [review]
We seem to have a failing test now, @vincentraymond-ua : https://github.com/ml4ai/skema/actions/runs/6489374835/job/17623516511#step:14:85

Can you please take a look?

**Comment by vincentraymond-ua** [comment]
It looks like this is caused by a change on the Rust side, I will look into it.

**Review by titomeister — APPROVED** [review]
Looks good to me!

**Review by myedibleenso — APPROVED** [review]

**Pull request merged**
